### PR TITLE
Bump bounds on base and template-haskell.

### PR DESCRIPTION
**Pull request by athas**
This allows building with GHC 9.4.

### CODE REVIEW

**Comment by fumieval** [comment]
@athas Sadly there's a conflict due to a change in the adjacent line. Could you rebase the branch on master?

**Comment by athas** [comment]
I have resolved the conflicts with a merge, not a rebase.  I hope that's OK.

**Comment by fumieval** [comment]
Rebase is preferable but I guess that's OK because it can be squash-merged on GitHub anyway

**Comment by fumieval** [comment]
Thanks

**Pull request merged**
