### PR TITLE
Allow building with `vector-0.13.*`

### LINKED ISSUE #8: Allow building with `vector-0.13.*`
As far as I can tell, `vector-th-unbox`'s upper version bounds on `vector` can be raised to support `vector-0.13.*` without needing any other code changes.

### PR DESCRIPTION
**Pull request by RyanGlScott**
Fixes #8.

### CODE REVIEW

**Comment by Fuuzetsu** [comment]
Forgot to reply to original ticket. Is a Hackage revision more convenient or is a new minor release better for you?

**Comment by RyanGlScott** [comment]
A Hackage revision would suffice. Thanks!

**Comment by Fuuzetsu** [comment]
@fumieval seems no-one that's left in Tsuru has package maintainer access, can you make the cabal revision and/or add someone from Tsuru to maintainers on Hackage?

I guess I should also add you to this repo as collaborator.

**Comment by fumieval** [comment]
@Fuuzetsu I thought I added maoe as a maintainer, but not this one apparently... I've just added [MateuszKowalczyk](https://hackage.haskell.org/user/MateuszKowalczyk) and [MitsutoshiAoe](https://hackage.haskell.org/user/MitsutoshiAoe) as maintainers.

I made a Hackage revision too: https://hackage.haskell.org/package/vector-th-unbox-0.2.2/revisions/

I missed the invitation and it has expired; can you re-invite me?

**Comment by Fuuzetsu** [comment]
> @Fuuzetsu I thought I added maoe as a maintainer, but not this one apparently... I've just added [MateuszKowalczyk](https://hackage.haskell.org/user/MateuszKowalczyk) and [MitsutoshiAoe](https://hackage.haskell.org/user/MitsutoshiAoe) as maintainers.

I see it, thanks!

> I made a Hackage revision too: https://hackage.haskell.org/package/vector-th-unbox-0.2.2/revisions/

Great.

> I missed the invitation and it has expired; can you re-invite me?

Sent. Feel free to close the issue once you accept.

**Comment by fumieval** [comment]
Thanks! I accepted the invitation.

**Pull request merged**
